export const COUNTRY_CODES = [
  { code: '+1', label: '+1 🇺🇸/🇨🇦', name: 'USA/Canada' },
  { code: '+20', label: '+20 🇪🇬', name: 'Egypt' },
  { code: '+27', label: '+27 🇿🇦', name: 'South Africa' },
  { code: '+30', label: '+30 🇬🇷', name: 'Greece' },
  { code: '+31', label: '+31 🇳🇱', name: 'Netherlands' },
  { code: '+32', label: '+32 🇧🇪', name: 'Belgium' },
  { code: '+33', label: '+33 🇫🇷', name: 'France' },
  { code: '+34', label: '+34 🇪🇸', name: 'Spain' },
  { code: '+36', label: '+36 🇭🇺', name: 'Hungary' },
  { code: '+39', label: '+39 🇮🇹', name: 'Italy' },
  { code: '+40', label: '+40 🇷🇴', name: 'Romania' },
  { code: '+41', label: '+41 🇨🇭', name: 'Switzerland' },
  { code: '+43', label: '+43 🇦🇹', name: 'Austria' },
  { code: '+44', label: '+44 🇬🇧', name: 'UK' },
  { code: '+45', label: '+45 🇩🇰', name: 'Denmark' },
  { code: '+46', label: '+46 🇸🇪', name: 'Sweden' },
  { code: '+47', label: '+47 🇳🇴', name: 'Norway' },
  { code: '+48', label: '+48 🇵🇱', name: 'Poland' },
  { code: '+49', label: '+49 🇩🇪', name: 'Germany' },
  { code: '+51', label: '+51 🇵🇪', name: 'Peru' },
  { code: '+52', label: '+52 🇲🇽', name: 'Mexico' },
  { code: '+53', label: '+53 🇨🇺', name: 'Cuba' },
  { code: '+54', label: '+54 🇦🇷', name: 'Argentina' },
  { code: '+55', label: '+55 🇧🇷', name: 'Brazil' },
  { code: '+56', label: '+56 🇨🇱', name: 'Chile' },
  { code: '+57', label: '+57 🇨🇴', name: 'Colombia' },
  { code: '+58', label: '+58 🇻🇪', name: 'Venezuela' },
  { code: '+591', label: '+591 🇧🇴', name: 'Bolivia' },
  { code: '+593', label: '+593 🇪🇨', name: 'Ecuador' },
  { code: '+595', label: '+595 🇵🇾', name: 'Paraguay' },
  { code: '+598', label: '+598 🇺🇾', name: 'Uruguay' },
  { code: '+60', label: '+60 🇲🇾', name: 'Malaysia' },
  { code: '+61', label: '+61 🇦🇺', name: 'Australia' },
  { code: '+62', label: '+62 🇮🇩', name: 'Indonesia' },
  { code: '+63', label: '+63 🇵🇭', name: 'Philippines' },
  { code: '+64', label: '+64 🇳🇿', name: 'New Zealand' },
  { code: '+65', label: '+65 🇸🇬', name: 'Singapore' },
  { code: '+66', label: '+66 🇹🇭', name: 'Thailand' },
  { code: '+7', label: '+7 🇷🇺', name: 'Russia/Kazakhstan' },
  { code: '+81', label: '+81 🇯🇵', name: 'Japan' },
  { code: '+82', label: '+82 🇰🇷', name: 'South Korea' },
  { code: '+84', label: '+84 🇻🇳', name: 'Vietnam' },
  { code: '+86', label: '+86 🇨🇳', name: 'China' },
  { code: '+90', label: '+90 🇹🇷', name: 'Turkey' },
  { code: '+91', label: '+91 🇮🇳', name: 'India' },
  { code: '+92', label: '+92 🇵🇰', name: 'Pakistan' },
  { code: '+93', label: '+93 🇦🇫', name: 'Afghanistan' },
  { code: '+94', label: '+94 🇱🇰', name: 'Sri Lanka' },
  { code: '+95', label: '+95 🇲🇲', name: 'Myanmar' },
  { code: '+98', label: '+98 🇮🇷', name: 'Iran' },
  { code: '+212', label: '+212 🇲🇦', name: 'Morocco' },
  { code: '+213', label: '+213 🇩🇿', name: 'Algeria' },
  { code: '+216', label: '+216 🇹🇳', name: 'Tunisia' },
  { code: '+234', label: '+234 🇳🇬', name: 'Nigeria' },
  { code: '+254', label: '+254 🇰🇪', name: 'Kenya' },
  { code: '+351', label: '+351 🇵🇹', name: 'Portugal' },
  { code: '+353', label: '+353 🇮🇪', name: 'Ireland' },
  { code: '+358', label: '+358 🇫🇮', name: 'Finland' },
  { code: '+375', label: '+375 🇧🇾', name: 'Belarus' },
  { code: '+380', label: '+380 🇺🇦', name: 'Ukraine' },
  { code: '+420', label: '+420 🇨🇿', name: 'Czechia' },
  { code: '+421', label: '+421 🇸🇰', name: 'Slovakia' },
  { code: '+502', label: '+502 🇬🇹', name: 'Guatemala' },
  { code: '+503', label: '+503 🇸🇻', name: 'El Salvador' },
  { code: '+504', label: '+504 🇭🇳', name: 'Honduras' },
  { code: '+505', label: '+505 🇳🇮', name: 'Nicaragua' },
  { code: '+506', label: '+506 🇨🇷', name: 'Costa Rica' },
  { code: '+507', label: '+507 🇵🇦', name: 'Panama' },
  { code: '+852', label: '+852 🇭🇰', name: 'Hong Kong' },
  { code: '+886', label: '+886 🇹🇼', name: 'Taiwan' },
  { code: '+966', label: '+966 🇸🇦', name: 'Saudi Arabia' },
  { code: '+971', label: '+971 🇦🇪', name: 'UAE' },
  { code: '+972', label: '+972 🇮🇱', name: 'Israel' },
].sort((a, b) => a.code.localeCompare(b.code, undefined, { numeric: true }));
